### ISSUE TITLE
Develop components of prototype with 1-to-1-relationship

### ISSUE THREAD

**Issue by fyndalf** [BPChain/chainboard-prototype#9]
As a developer I want the prototype to have a 1-to-1 relationship between all components so that I can focus on the core features.

Acceptance criteria:
- [x] Infrastructure is running as displayed in our diagram, with a single UI, proxy server, and Docker Swarm.

**Comment by fyndalf** [comment]
Acceptance criteria:
- [ ] Infrastructure is running as displayed in our diagram, with a single UI, proxy server, and Docker Swarm.

**Comment by t-lichtenstein** [comment]
Issue moved to [BPChain/meta #1](https://github.com/BPChain/meta/issues/1) via [**ZenHub**](https://www.zenhub.com/)
